const defaults={products:[
{id:"p1",name:"Luxe Bone Straight",price:165000,salePrice:130000,detail:'22” • 200% • HD Lace',category:"Bone Straight",hotDeal:true,bestseller:true,available:true,image:"https://images.unsplash.com/photo-1562322140-8baeececf3df?auto=format&fit=crop&w=900&q=85"},
{id:"p2",name:"Dreamy Curls",price:182000,salePrice:149000,detail:'20” • 180% • HD Lace',category:"Curly",hotDeal:true,bestseller:true,available:true,image:"https://images.unsplash.com/photo-1580618672591-eb180b1a973f?auto=format&fit=crop&w=900&q=85"},
{id:"p3",name:"Classic Bob",price:145000,salePrice:119000,detail:'14” • 180% • HD Lace',category:"Bob Wigs",hotDeal:true,bestseller:true,available:true,image:"https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=900&q=85"},
{id:"p4",name:"Piano Highlight",price:205000,detail:'22” • 200% • HD Lace',category:"Coloured Wigs",hotDeal:false,bestseller:true,available:true,image:"https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=900&q=85"}],
reviews:[{id:"r1",name:"Amara T.",rating:5,quote:"The hair is so soft and true to length. I keep getting compliments.",published:true,image:"https://images.unsplash.com/photo-1531123897727-8f129e1688ce?auto=format&fit=crop&w=500&q=80"}],
announcements:[{id:"a1",message:"Global delivery available • 3–6 day nationwide shipping",active:true}]};
const get=k=>{try{return JSON.parse(localStorage.getItem("hbg_"+k))||defaults[k]}catch{return defaults[k]}};const save=(k,v)=>localStorage.setItem("hbg_"+k,JSON.stringify(v));const id=p=>p+"_"+Date.now();let tab="home";
document.querySelectorAll("[data-tab]").forEach(b=>b.onclick=()=>{tab=b.dataset.tab;document.querySelectorAll("[data-tab]").forEach(x=>x.classList.toggle("active",x===b));render()});
function home(){const p=get("products"),r=get("reviews"),a=get("announcements");return `<h1 class="admin-title">Welcome back, Giftee</h1><p class="muted">Keep your website fresh in a few clicks.</p><div class="quick"><button data-go="products">＋<b>Add Product</b></button><button data-go="announcements">✦<b>Announcement</b></button><button data-go="deals">🔥<b>Hot Deal</b></button><button data-go="reviews">★<b>Add Review</b></button></div><div class="panel"><b>At a glance</b><p>${p.length} products • ${p.filter(x=>x.hotDeal).length} hot deals • ${r.filter(x=>x.published!==false).length} reviews</p><p class="muted">Current announcement: ${(a.find(x=>x.active)||{}).message||"None"}</p></div>`}
function products(){const items=get("products");return `<h1 class="admin-title">Products</h1><p class="muted">Add a wig or update what’s already on the website.</p><form id="productForm" class="panel form-grid"><label class="field">Product name<input name="name" required placeholder="Luxe Bone Straight"></label><label class="field">Price (₦)<input name="price" type="number" required placeholder="165000"></label><label class="field full">Hair details<input name="detail" placeholder='22” • 200% • HD Lace'></label><label class="field full">Photo URL<input name="image" placeholder="https://..."></label><label class="check"><input name="available" type="checkbox" checked> Available</label><label class="check"><input name="bestseller" type="checkbox"> Bestseller</label><div class="field full"><button class="btn primary">Add Product</button></div></form><div class="panel admin-list">${items.map(p=>`<div class="row"><div><b>${p.name}</b><br><small>${p.detail||""} • ₦${Number(p.price).toLocaleString()}</small></div><span>${p.available===false?"Sold out":"Available"}</span><div class="row-actions"><button class="mini" data-toggle-product="${p.id}">${p.available===false?"Make available":"Mark sold out"}</button><button class="mini danger" data-delete-product="${p.id}">Delete</button></div></div>`).join("")}</div>`}
function deals(){const items=get("products");return `<h1 class="admin-title">Hot Deals</h1><p class="muted">Choose a product and set its deal price.</p><form id="dealForm" class="panel form-grid"><label class="field">Product<select name="product">${items.map(p=>`<option value="${p.id}">${p.name}</option>`).join("")}</select></label><label class="field">Sale price (₦)<input name="salePrice" type="number" required></label><div class="field full"><button class="btn primary">Publish Deal</button></div></form><div class="panel admin-list">${items.filter(p=>p.hotDeal).map(p=>`<div class="row"><div><b>${p.name}</b><br><small>₦${Number(p.price).toLocaleString()} → ₦${Number(p.salePrice||0).toLocaleString()}</small></div><span>Hot deal</span><button class="mini danger" data-remove-deal="${p.id}">Remove</button></div>`).join("")||"<p>No hot deals yet.</p>"}</div>`}
function announcements(){const items=get("announcements");return `<h1 class="admin-title">Announcements</h1><p class="muted">Show one short message at the top of your website.</p><form id="announcementForm" class="panel"><label class="field">Message<textarea name="message" maxlength="160" required placeholder="Free delivery on orders above ₦100,000 ❤️"></textarea></label><br><button class="btn primary">Publish Announcement</button></form><div class="panel admin-list">${items.map(a=>`<div class="row"><div><b>${a.message}</b><br><small>${a.active?"Showing":"Hidden"}</small></div><button class="mini" data-show-ann="${a.id}">${a.active?"Hide":"Show"}</button><button class="mini danger" data-delete-ann="${a.id}">Delete</button></div>`).join("")}</div>`}
function reviews(){const items=get("reviews");return `<h1 class="admin-title">Reviews</h1><p class="muted">Add feedback from a happy customer.</p><form id="reviewForm" class="panel form-grid"><label class="field">Customer name<input name="name" required placeholder="Tola A."></label><label class="field">Rating<select name="rating"><option>5</option><option>4</option><option>3</option></select></label><label class="field full">Customer photo URL<input name="image" placeholder="https://..."></label><label class="field full">What did they say?<textarea name="quote" required></textarea></label><div class="field full"><button class="btn primary">Add Review</button></div></form><div class="panel admin-list">${items.map(r=>`<div class="row"><div><b>${r.name} • ${"★".repeat(r.rating||5)}</b><br><small>“${r.quote}”</small></div><button class="mini" data-toggle-review="${r.id}">${r.published===false?"Show":"Hide"}</button><button class="mini danger" data-delete-review="${r.id}">Delete</button></div>`).join("")}</div>`}
function render(){const s=document.querySelector("#screen");s.innerHTML=tab==="home"?home():tab==="products"?products():tab==="deals"?deals():tab==="announcements"?announcements():reviews();s.querySelectorAll("[data-go]").forEach(b=>b.onclick=()=>{tab=b.dataset.go;document.querySelectorAll("[data-tab]").forEach(x=>x.classList.toggle("active",x.dataset.tab===tab));render()});
const pf=s.querySelector("#productForm");if(pf)pf.onsubmit=e=>{e.preventDefault();const f=new FormData(pf),v=get("products");v.unshift({id:id("p"),name:f.get("name"),price:Number(f.get("price")),detail:f.get("detail"),image:f.get("image")||"https://images.unsplash.com/photo-1562322140-8baeececf3df?auto=format&fit=crop&w=900&q=85",available:f.get("available")==="on",bestseller:f.get("bestseller")==="on"});save("products",v);render()};
s.querySelectorAll("[data-delete-product]").forEach(b=>b.onclick=()=>{save("products",get("products").filter(x=>x.id!==b.dataset.deleteProduct));render()});s.querySelectorAll("[data-toggle-product]").forEach(b=>b.onclick=()=>{save("products",get("products").map(x=>x.id===b.dataset.toggleProduct?{...x,available:x.available===false}:x));render()});
const df=s.querySelector("#dealForm");if(df)df.onsubmit=e=>{e.preventDefault();const f=new FormData(df);save("products",get("products").map(x=>x.id===f.get("product")?{...x,hotDeal:true,salePrice:Number(f.get("salePrice"))}:x));render()};s.querySelectorAll("[data-remove-deal]").forEach(b=>b.onclick=()=>{save("products",get("products").map(x=>x.id===b.dataset.removeDeal?{...x,hotDeal:false,salePrice:null}:x));render()});
const af=s.querySelector("#announcementForm");if(af)af.onsubmit=e=>{e.preventDefault();const f=new FormData(af);save("announcements",[{id:id("a"),message:f.get("message"),active:true},...get("announcements").map(x=>({...x,active:false}))]);render()};s.querySelectorAll("[data-show-ann]").forEach(b=>b.onclick=()=>{const target=b.dataset.showAnn;save("announcements",get("announcements").map(x=>({...x,active:x.id===target?!x.active:false})));render()});s.querySelectorAll("[data-delete-ann]").forEach(b=>b.onclick=()=>{save("announcements",get("announcements").filter(x=>x.id!==b.dataset.deleteAnn));render()});
const rf=s.querySelector("#reviewForm");if(rf)rf.onsubmit=e=>{e.preventDefault();const f=new FormData(rf);save("reviews",[{id:id("r"),name:f.get("name"),rating:Number(f.get("rating")),image:f.get("image")||"https://images.unsplash.com/photo-1531123897727-8f129e1688ce?auto=format&fit=crop&w=500&q=80",quote:f.get("quote"),published:true},...get("reviews")]);render()};s.querySelectorAll("[data-toggle-review]").forEach(b=>b.onclick=()=>{save("reviews",get("reviews").map(x=>x.id===b.dataset.toggleReview?{...x,published:x.published===false}:x));render()});s.querySelectorAll("[data-delete-review]").forEach(b=>b.onclick=()=>{save("reviews",get("reviews").filter(x=>x.id!==b.dataset.deleteReview));render()})}
render();